name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      env:
        TARGET_PATH: ${{ env.GITHUB_ACTION_PATH }}
      run: | 
         export CONTRACTS_NODE=${{ TARGET_PATH }}/target/debug/node-template
         echo $CONTRACTS_NODE
         echo "Ok ${{ github.action_path }}"
   
